---
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "plcnk"
    target-branch: "dev"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "plcnk"
    target-branch: "dev"
