name: "CI"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script:
          - aws-ec2-instance
          - digitalocean-droplet
          - digitalocean-k8s-cluster

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=${{ matrix.script }} fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform -chdir=${{ matrix.script }} init
        continue-on-error: true
        
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=${{ matrix.script }} validate -no-color
        continue-on-error: true

      - name: Check status
        if: steps.fmt.outcome == 'failure' || steps.init.outcome == 'failure' || steps.validate.outcome == 'failure'
        run: exit 1
